---
names: 'Charlie Gels, Nick Russo, Daniel DeFoe'
title: "R Report"
date: '11/28/17'
output: html_notebook
---


#Report
###Overview
Our shiny app investigates the values of two of the world's main universal cryptocurrencies Bitcoin and Ethereum. Data of these 2 values from 2015 to 2017 are subsetted by business quarters to observe and predict various metrics of the currencies. The data is split into quarters because the nature of the cryptocurrency market has the values of the currency fluxuating excessively within short periods of time. By changing the time interval to quarters, some predictions are able to be made. 

###Packages
Our app uses a collection of packages to do its analysis and provide its output. 'Shiny' is used to create the actual app, 'Lubridate'  and 'Zoo' are used to appropriately format the dates and time series data, 'dplyer' is used to filter the data by whatever paremeters we want to view the data by, 'forecast' is used for predicting a range of values based on past observations, 'ggplot2' allows us to make the nice graphical output, and 'magrittr' allows us to pipe in values. The packages collectively allow for clean and straightforward output for the user. 

###Using the Shiny App
The app focuses on graphical output of the different variables for each currency, where the user can subset particular values to view, or view all available data. There are sliders to adjust the year, 

###Statistical Concepts
Using the quarterly data from 2015 to 2017, we have some limited prediction ability to create confidence intervals for various metrics of bitcoin and ethereum. 

###Conclusion
A simple glance at the data would correctly suggest that the market is quite volatile, but analyzing the data averaged over larger time periods shows that we do have some ability to predict upon the data.